name: CI Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: devsecops-demo-app
  ECR_REGISTRY: 676591241638.dkr.ecr.us-east-1.amazonaws.com

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: "1"
          ignore-unfixed: true

      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: docker build -t devsecops-demo-app:${{ github.sha }} .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-demo-app:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: "1"
          ignore-unfixed: true

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::676591241638:role/GitHubActions-DevSecOps-ECR
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image to ECR
        if: github.event_name == 'push'
        run: |
          IMAGE_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ github.sha }}
          docker tag devsecops-demo-app:${{ github.sha }} "$IMAGE_URI"
          docker push "$IMAGE_URI"
